"""
These are the inputs for a real post that will
be automatically published. You can see the
`reminders.py` file to get a notification
instead of the post published.

The automatic post can have fields that are only
available for the paid plan. By now we are
disabling them.

TODO: Implement a 'PaidMetadataInput' (?)
"""
from bufferpy.inputs.platforms.instagram.consts import PLATFORM
from bufferpy.inputs.platforms.base import _PlatformMetadataInput
from bufferpy.enums import PostType
from dataclasses import dataclass, field
from typing import ClassVar


@dataclass(slots = True)
class InstagramReelMetadataInput(
    _PlatformMetadataInput
):
    """
    Metadata for an instagram post that is a reel.
    """

    platform: ClassVar[str] = PLATFORM
    type: PostType = field(default = PostType.REEL, init = False)

    do_share_to_feed: bool = True
    """
    Boolean flag to indicate if the post has to
    be shared to the feed or not.
    """
    is_ai_generated: bool = False
    """
    Boolean flag to indicate if the content has
    been generated by AI or not.
    """
    # TODO: Paid plan required
    # first_comment: str = ''
    # """
    # The first comment we want to add to make the
    # people interact with the post, if we want it.
    # """

    __graphql_field_map__ = {
        'do_share_to_feed': 'shouldShareToFeed',
        'is_ai_generated': 'isAiGenerated',
        # TODO: Paid plan required
        # 'first_comment': 'firstComment',
    }

    # Due to bug in python 3.10...
    def __post_init__(
        self
    ):
        object.__setattr__(self, 'type', PostType.REEL)



@dataclass(slots = True)
class InstagramPostMetadataInput(
    _PlatformMetadataInput
):
    """
    Metadata for an instagram post that is a post.

    A post can never have a video as asset.
    """

    platform: ClassVar[str] = PLATFORM
    type: PostType = field(default = PostType.POST, init = False)

    # TODO: This doesn't appear in the web app
    do_share_to_feed: bool = True
    """
    Boolean flag to indicate if the post has to
    be shared to the feed or not.
    """
    # TODO: Paid plan required
    # first_comment: str = ''
    # """
    # The first comment we want to add to make the
    # people interact with the post, if we want it.
    # """
    is_ai_generated: bool = False
    """
    Boolean flag to indicate if the content has
    been generated by AI or not.
    """

    __graphql_field_map__ = {
        'do_share_to_feed': 'shouldShareToFeed',
        'is_ai_generated': 'isAiGenerated',
        # TODO: Paid plan required
        # 'first_comment': 'firstComment',
    }

    # Due to bug in python 3.10...
    def __post_init__(
        self
    ):
        object.__setattr__(self, 'type', PostType.POST)


# TODO: Untested
@dataclass(slots = True)
class InstagramStoryMetadataInput(
    _PlatformMetadataInput
):
    """
    Metadata for an instagram post that is a story.
    """

    platform: ClassVar[str] = PLATFORM
    type: PostType = field(default = PostType.STORY, init = False)

    # TODO: This doesn't appear in the web app
    do_share_to_feed: bool = True
    """
    Boolean flag to indicate if the post has to
    be shared to the feed or not.
    """
    is_ai_generated: bool = False
    """
    Boolean flag to indicate if the content has
    been generated by AI or not.
    """

    __graphql_field_map__ = {
        'do_share_to_feed': 'shouldShareToFeed',
        'is_ai_generated': 'isAiGenerated'
    }

    # Due to bug in python 3.10...
    def __post_init__(
        self
    ):
        object.__setattr__(self, 'type', PostType.STORY)




"""
TODO: What about these other fields?
- geolocation
- annotations
"""