"""
The functionality related to Tiktok.

The Buffer platform API allows you to schedule
posts that will be automatically published, or
to schedule reminders that will be notified to
your phone.

Check the official docummentation here:
- https://developers.buffer.com/types/TiktokPostMetadata.html
"""
from bufferpy.inputs.platforms.tiktok.consts import PLATFORM
from bufferpy.inputs.platforms.base import _PlatformMetadataInput
from dataclasses import dataclass
from typing import ClassVar


@dataclass(slots = True)
class TiktokReelMetadataInput(
    _PlatformMetadataInput
):
    """
    Metadata for a Tiktok post that is a reel.
    """

    platform: ClassVar[str] = PLATFORM

    is_ai_generated: bool = False
    """
    Boolean flag to indicate if the content has
    been generated by AI or not.

    TODO: Apparently for videos only
    """
    title: str = ''
    """
    A title for the post.

    TODO: Apparently for images only.
    """

    __graphql_field_map__ = {
        'is_ai_generated': 'isAiGenerated',
    }